version: '3'

services:
  auth:
    build:
      context: ./courses_service
      dockerfile: ./courses_service/DockerfileCourse
    ports:
      - "8000:8000"
    restart: always
  
  course:
    build:
      context: ./authentication_service
      dockerfile: ./authentication_service/DockerfileAuth
    ports:
      - "8001:8001"
    depends_on:
      - auth
    restart: always
