version: '3'

services:
  courses:
    build:
      context: .
      dockerfile: ./courses_service/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - my-network
    volumes:
      - ./courses_service:/app
    restart: always
    depends_on:
      - auth

  auth:
    build:
      context: .
      dockerfile: ./authentication_service/Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./authentication_service:/app
    networks:
      - my-network
    restart: always

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - courses
      - auth
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

