version: '3'

services:
  courses:
    build:
      context: .
      dockerfile: ./courses_service/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - my-network
    restart: always
    links:
      - auth
    depends_on:
      - auth

  auth:
    build:
      context: .
      dockerfile: ./authentication_service/Dockerfile
    ports:
      - "8001:8001"
    networks:
      - my-network
    restart: always

networks:
  my-network:
    driver: bridge

